name: CI Android

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Which NDK
        run: ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --list --channel=0 | grep NDK # 0 (stable), 1 (beta), 2 (dev), or 3 (canary)
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install 'ndk;24.0.8215888' 1>/dev/null
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive Lint report
        uses: actions/upload-artifact@v3.1.0
        if: ${{ always() }}
        with:
          name: PGL-Lint-report
          path: ./**/build/intermediates/lint_intermediate_text_report/debug/lint-results-debug.txt